version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/daily-report

permissions:
  - object: /home/ec2-user/daily-report
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/install_and_migrate.sh
      timeout: 3000
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
