version: '2'
services:
  db:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    volumes:
      - mysql-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: daily-report_development
  app:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    volumes:
      - .:/daily-report
      - rubygems:/usr/local/bundle
    ports:
      - "3456:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
      DB_HOST:
      DB_USERNAME:
      DB_PASSWORD:
      BUGSNAG_API_KEY:
      BUGSNAG_ENV:
      SLACK_WEBHOOK_URL:
    command: /bin/bash -c "bin/rails s -b 0.0.0.0 -p 3000"

volumes:
  rubygems:
    driver: 'local'
  mysql-db:
    driver: 'local'
