version: '3.7'

services:
  db-ci:
    image: mysql:5.7
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: daily_report_test
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  app-ci:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile.ci
    volumes:
      - .:/daily-report
      - rubygems-ci:/usr/local/bundle
      - node_modules-ci:/daily-report/node_modules
    depends_on:
      - db-ci
    environment:
      RAILS_ENV: test
      NODE_ENV: test
      MYSQL_HOST: db-ci
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_PORT: 3306
      DB_HOST: db-ci
      DB_USERNAME: root
      DB_PASSWORD: password
      DB_PORT: 3306
      BUNDLER_VERSION: 2.4.22
      CI: "true"
      HEADLESS: "true"
      DISABLE_SPRING: "true"
    command: >
      bash -c "
        gem update --system 3.3.22 &&
        gem install bundler &&
        bundle install &&
        yarn install --frozen-lockfile &&
        yarn build &&
        bundle exec rails db:create &&
        bundle exec rails db:migrate &&
        bundle exec rails db:seed &&
        mkdir -p tmp/screenshots &&
        echo 'Verifying Turbo configuration...' &&
        bundle exec rails runner 'puts \"Turbo enabled: \" + Rails.application.config.turbo.to_s' &&
        echo 'Running RSpec tests...' &&
        bundle exec rspec spec/features/ --format documentation --format progress --backtrace
      "

volumes:
  rubygems-ci:
    driver: 'local'
  node_modules-ci:
    driver: 'local'