version: '2'
services:
  app:
    build: .
    command: ["bin/rails", "server", "-p", "3000", "-b", "0.0.0.0"]
    environment:
      RAILS_ENV: development
      MYSQL_HOST: mysql
    ports:
      - '3456:3000'
    volumes:
      - .:/daily-report
    depends_on:
      - mysql
      - memcached
    volumes_from:
      - bundle

  mysql_data:
    image: busybox
    volumes:
      - /var/lib/mysql

  mysql:
    image: 'mysql:5.7.16'
    volumes_from:
      - mysql_data
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

  memcached:
    image: 'memcached:1.4'

  bundle:
    image: busybox
    volumes:
      - /bundle
