version: '2'
services:
  app:
    build: .
    environment:
      RAILS_ENV: development
      MYSQL_HOST: mysql
    ports:
      - '6000:3000'
    volumes:
      - .:/daily-report
    links:
      - mysql
      - memcached
    volumes_from:
      - bundle
  mysql:
    image: 'mysql:5.7.16'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  memcached:
    image: 'memcached:1.4'
  bundle:
    image: busybox
    volumes:
      - /bundle
