version: 2
jobs:
  deploy_production:
    docker:
      - image: circleci/ruby:2.4-node
        environment:
          AWS_CODE_DEPLOY_REGION: ap-northeast-1
          AWS_CODE_DEPLOY_APPLICATION_NAME: daily-report
          AWS_CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: daily-report-production
          AWS_CODE_DEPLOY_S3_BUCKET: deploy.daily-report.xtone.co.jp
    steps:
      - checkout
      - run:
          name: install aws-code-deploy
          command: sudo npm install aws-code-deploy -g
      - run:
          name: setup environment dynamically
          command: |
            echo "export AWS_CODE_DEPLOY_APP_SOURCE=${CIRCLE_WORKING_DIRECTORY}" >> $BASH_ENV
            echo "export AWS_CODE_DEPLOY_S3_FILENAME=daily-report-${CIRCLE_BUILD_NUM}-${CIRCLE_BRANCH}-${CIRCLE_SHA1}" >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: deploy to production
          command: aws-code-deploy

workflows:
  version: 2
  deploy:
    jobs:
      - deploy_production:
          filters:
            branches:
              only: master
