version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1.4
jobs:
  deploy:
    working_directory: ~/deployment-archive
    docker:
      - image: naughtldy/circleci-node-awscli:8
    steps:
      - checkout
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_REGION
      - run:
          name: zip
          command: zip -r master ../deployment-archive
      - run:
          name: zip upload
          command: aws s3 cp master.zip s3://deploy.daily-report.xtone.co.jp/daily-report-${CIRCLE_BRANCH}-${CIRCLE_SHA1} --region ap-northeast-1
      - run:
          name: deploy production
          command: |
            aws deploy create-deployment \
              --application-name daily-report \
              --deployment-group-name daily-report-production \
              --s3-location bucket="deploy.daily-report.xtone.co.jp",bundleType="zip",eTag=`aws s3api head-object --bucket deploy.daily-report.xtone.co.jp --key daily-report-${CIRCLE_BRANCH}-${CIRCLE_SHA1} | jq .ETag`,key="daily-report-${CIRCLE_BRANCH}-${CIRCLE_SHA1}" \
              --region ap-northeast-1

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
