name: RuboCop

on:
  pull_request:
    branches: [ develop, main, master ]

jobs:
  rubocop:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.8
        bundler-cache: true

    - name: Run RuboCop
      run: |
        bundle exec rubocop --parallel --format github