name: Security

on:
  push:
    branches: [ develop, main, master ]
  pull_request:
    branches: [ develop, main, master ]
  schedule:
    # 毎週月曜日の午前9時（JST）に実行
    - cron: '0 0 * * 1'

jobs:
  brakeman:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.8
        bundler-cache: true

    - name: Run Brakeman
      run: |
        bundle exec brakeman -q -w2 --format github

  bundler-audit:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.8
        bundler-cache: true

    - name: Install bundler-audit
      run: |
        gem install bundler-audit

    - name: Run bundler-audit
      run: |
        bundle audit check --update